server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka 服务端的实例名称 单机
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false # 表示自己就是注册中心，维护服务实例，不需要检索服务
    service-url:
      #设置与Eureka server交互的地址，查询服务和注册服务都需要这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机
      defaultZone: http://eureka7001.com:7001/eureka/ #集群互相注册
